# Set 1: Vectorized code and introduction to machine learning

## Task 1c)

In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

y = a @ b
print(y)

550


## Task 1d)

In [3]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([10,11,12])

y = X @ b
print(y)

[ 68 167 266]


## Task 1e)

In [5]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([10,11,12])

y = (X @ b).sum()
print(y)

501


## Task 1f)

In [18]:

Z = np.array([[7,8],[9,10],[11,12],[13,14]])   # Z is a PxM matrix. Here P=4 and M=2

X = np.array([[1,2,3,4],
              [5,6,7,8]])  # X is a MxN matrix. Here M=2 and N=4

Y = Z @ X   # This should be a PxN matrix (here 4x4)
print (Y)

# Now, we could simply sum each column to get the desired result:
Y = Y.sum(axis=0)

# In one operation
Y = (Z @ X).sum(axis=0)
print (Y)

[[ 47  62  77  92]
 [ 59  78  97 116]
 [ 71  94 117 140]
 [ 83 110 137 164]]
[260 344 428 512]


## Task 1g)

In [20]:
# Samples. Here we have N=3 samples with n=5 features. Each sample is a row-vector in X.

X = np.array([[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15]])  # Nxn matrix

# Parameter vector. These parameters takes each sample from R^n and maps them to R^P
# Here we have chosen P=4

w = np.array([[1, 2, 3, -1],
     [4, 5, 6, -2],
     [7, 8, 9, -3],
     [10, 11, 12, -4],
     [13, 14, 15, -5]])    # nxP matrix

# "Weight" vector a. This vector should be in R^P, where P=4 in this case

a= np.array([10, 20, 30, -10]).transpose()   #Transpose it to make it a column vector Px1

v = X @ w    # Will form a NxP matrix

y = v @ a    # Will form a Nx1 row vector, N=3

print(y)


## Task 1h)

In [34]:
from numpy import ndarray

def matrix_multiply(X: ndarray, Y: ndarray) :

    if X.ndim != 2 or Y.ndim != 2:
        raise Exception("We only accept ndarrays with the shape of matrixes (two dimensions)")

    print(X.shape)
    print(Y.shape)

    if X.shape[1] != Y.shape[0] :
        raise Exception("Number of columns in X must equal number of rows in Y")

    # We have now established a valid multiplication of a nxm with a mxp matrix.
    n = X.shape[0]
    m = X.shape[1]
    p = Y.shape[1]

    # Now do the matrix multiplications

    Z = ndarray(n,p)
    for i=0 to n






X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

b = np.array([[10,11,12]]).T

matrix_multiply(X,b)




(4, 3)
(3, 1)
